import type { Metadata } from "next";
import { Geist_Mono, Archivo } from "next/font/google";
import "./globals.css";

import Header from "@/components/ui/Header";
import CustomCursor from "@/components/ui/CustomCursor";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({
  variable: "--font-archivo-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistMono.variable} ${archivo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CustomCursor />
        <Header />
        {children}
      </body>
    </html>
  );
}
